version: "3"
services:
  django-backend:
    build: ./backend
    container_name: django-backend
    restart: always
    ports:
      - 8000:8000

  vue-frontend:
    build: ./frontend
    container_name: vue-frontend
    restart: always
    ports:
      - 8080:8080
